security:
    password_hashers:
        App\SecurityModule\Domain\Entity\User: 'auto'

    providers:
        users:
            id: App\SecurityModule\Infrastructure\Doctrine\Repository\UserRepository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users
            logout:
                path: app_logout
                target: app_login
            # remember_me: # optionnel
            #   secret: '%kernel.secret%'
            #   lifetime: 1209600

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/private, roles: ROLE_USER }
